'use client'

import { useEffect, useState } from 'react'

const V='2026-08-v1', SEEN=`cbs_demo_seen:rapid-takeoff:${V}`, DISMISSED=`cbs_demo_dismissed:rapid-takeoff:${V}`
const STEPS=[
  ['Choose the trade first','Select the trade you are estimating before uploading plans so the takeoff is scoped to the right materials, systems, and labor.'],
  ['Enter the known project facts','Ceiling Height is required. Add project type, drawing scale, square footage, floors, location, and labor rate whenever you know them; missing fields should stay unknown rather than guessed.'],
  ['Capture or upload plans','Take blueprint pictures with the camera or upload multiple drawing/image/PDF files. Review the thumbnails and remove anything that does not belong to the project.'],
  ['Run Rapid Matrix Engine™','Start analysis after the required inputs and plan files are ready. Large plan sets may work better in smaller batches if the network times out.'],
  ['Read confidence before quantities','Use Verified, Probable, Needs Review, and Conflict Radar counts to see where the estimate is strong and where field or drawing verification is still needed.'],
  ['Use ProofTrace™ and SheetLink™','Follow the report sections back to the drawing evidence and cross-sheet relationships instead of treating a generated quantity as a black-box answer.'],
  ['Resolve conflicts and missing information','Conflict Radar™ and Mandatory Missing Information are there to stop false precision. Verify discrepancies, scale issues, unclear notes, or missing dimensions before bidding.'],
  ['Deliver the estimate','Use PDF / Print or Email after the review queue is cleared enough for your purpose. Rapid Takeoff is an estimating aid; final quantities, code requirements, and bid commitments remain the contractor’s responsibility.'],
]

export default function DemoHelp(){
  const [open,setOpen]=useState(false),[dontShow,setDontShow]=useState(false)
  useEffect(()=>{try{if(localStorage.getItem(SEEN)!=='1'&&localStorage.getItem(DISMISSED)!=='1'){const t=setTimeout(()=>{localStorage.setItem(SEEN,'1');setOpen(true)},1100);return()=>clearTimeout(t)}}catch{}},[])
  const close=()=>{try{if(dontShow)localStorage.setItem(DISMISSED,'1')}catch{};setOpen(false)}
  return <><button onClick={()=>setOpen(true)} aria-label="How to use Rapid Takeoff" className="fixed right-4 bottom-4 z-[70] min-w-[58px] h-12 rounded-xl border border-orange-500/40 bg-zinc-900/95 text-zinc-100 font-black shadow-2xl">Help</button>{open&&<div onMouseDown={e=>{if(e.target===e.currentTarget)close()}} className="fixed inset-0 z-[1000] bg-black/80 backdrop-blur-md flex items-end md:items-center justify-center p-4"><section role="dialog" aria-modal="true" className="w-full max-w-2xl max-h-[90dvh] overflow-auto rounded-2xl border border-orange-500/30 bg-zinc-950 text-zinc-100 p-5 shadow-2xl"><div className="flex items-center justify-between gap-3"><div><div className="text-[10px] font-black tracking-[.18em] text-orange-500">CACTUS🌵BYTE GUIDED DEMO</div><h2 className="text-xl font-black mt-1">How to use Rapid Takeoff™</h2></div><button onClick={close} className="w-10 h-10 rounded-xl border border-zinc-700 bg-zinc-900 text-xl">×</button></div><p className="text-xs leading-relaxed text-zinc-400 mt-3">The fastest path from blueprint evidence to a reviewed takeoff and estimate.</p><div className="mt-3 rounded-xl border border-dashed border-orange-500/30 bg-zinc-900 p-4 text-xs leading-relaxed text-zinc-400"><strong className="text-zinc-200">60-second demo video slot ready.</strong><br/>The written walkthrough works now; the final recording can be dropped in after the current interface is locked.</div><div className="grid gap-2 mt-4">{STEPS.map(([t,x],i)=><div key={t} className="rounded-xl border border-zinc-800 bg-zinc-900/70 p-4"><strong className="text-sm text-orange-400">{i+1}. {t}</strong><p className="text-xs leading-relaxed text-zinc-400 mt-1 mb-0">{x}</p></div>)}</div><label className="flex items-start gap-2 mt-4 text-[11px] leading-relaxed text-zinc-500"><input type="checkbox" checked={dontShow} onChange={e=>setDontShow(e.target.checked)}/><span>Don’t show this automatically again for this demo version. The Help button stays available.</span></label><div className="flex gap-2 mt-4"><button onClick={close} className="flex-1 h-12 rounded-xl border border-zinc-700 bg-zinc-900 font-bold">Close</button><button onClick={()=>{document.querySelector('main')?.scrollIntoView({behavior:'smooth'});setOpen(false)}} className="flex-1 h-12 rounded-xl bg-orange-500 text-zinc-950 font-black">Start Takeoff</button></div></section></div>}</>
}
